version: '3.9'
services:
  db:
    container_name: server_db
    # image: postgres:16
    build: server
    restart: always
    shm_size: 128mb
    ports:
      - ${DB_PORT:-5432}:${DB_PORT:-5432}
    volumes:
      - ./server/data:/var/lib/postgresql/data
      # - ./server/src/db/db_init.sql:/docker-entrypoint-initdb.d/db_init.sql
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_SERVER:-server}

  adminer:
    container_name: db_console
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080