version: '3.9'
services:
  db:
    container_name: server_db
    build: server
    restart: always
    shm_size: 128mb
    ports:
      - 5432:5432
    volumes:
      - ./server/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: server

  adminer:
    container_name: db_console
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080