name: Test Server Application

on:
  push:
    branches:
    - main
    - release/*

jobs:
  test_server:
    name: Build & Test Server
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install Server Dependencies
        run: npm run install-server

      - name: Find and Replace DB Controller in Server Files with Mock Controller
        run: sed -i -e 's/.\/db\/controller/.\/db\/mock_controller/g' ./server/src/api_functions.ts

      - name: Build Server
        run: npm run build-server

      - name: Run Server Tests
        run: npm run test-server