name: Test Server Application

on:
  push:
    branches:
    - main
    - release/*

jobs:
  build_website_files:
    name: Build Files
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install Server Dependencies
        run: npm run install-server
        
      - name: Build Server
        run: npm run build-server

      - name: Replace DB Controller with Mock
        run: mv ./server/dist/src/db/mock_controller.js ./server/dist/src/db/controller.js

      - name: Check Directory Content
        run: cd ./server/dist/src/db/ && ls -al

      # - name: Run Tests
      #   run: npm test
