name: Test Server Application

on:
  push:
    branches:
    - main
    - release/*

jobs:
  build_website_files:
    name: Build Files
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      
      - name: Navigate to Server
        run: cd ./server

      - name: Install Dependencies
        run: npm install
        
      - name: Build Server
        run: npm run build

      - name: Replace DB Controller with Mock
        run: mv ./dist/src/db/mock_controller.js ./dist/src/db/controller.js

      - name: Run Tests
        run: npm test
